spring:
  application:
    name: ReactiveSpringBootApplication
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/test
    username: postgres
    password: postgres

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html